# Generated by Django 3.0.6 on 2020-05-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=11)),
                ('content', models.TextField()),
            ],
        ),
    ]
