# Generated by Django 3.0.6 on 2020-05-19 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='timestamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
