# Generated by Django 3.0.6 on 2020-05-24 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_orderupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
    ]
